ARG EE_BASE_IMAGE=registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8:1.0.0-209
ARG EE_BUILDER_IMAGE=quay.io/ansible/ansible-builder:latest

FROM $EE_BASE_IMAGE as galaxy
ARG ANSIBLE_GALAXY_CLI_COLLECTION_OPTS=
ARG ANSIBLE_GALAXY_CLI_ROLE_OPTS=
USER root

ADD _build/ansible.cfg ~/.ansible.cfg

ADD _build /build
WORKDIR /build

RUN ansible-galaxy role install $ANSIBLE_GALAXY_CLI_ROLE_OPTS -r requirements.yml --roles-path "/usr/share/ansible/roles"
RUN ANSIBLE_GALAXY_DISABLE_GPG_VERIFY=1 ansible-galaxy collection install $ANSIBLE_GALAXY_CLI_COLLECTION_OPTS -r requirements.yml --collections-path "/usr/share/ansible/collections"

FROM $EE_BUILDER_IMAGE as builder

COPY --from=galaxy /usr/share/ansible /usr/share/ansible

ADD _build/requirements.txt requirements.txt
ADD _build/bindep.txt bindep.txt
RUN ansible-builder introspect --sanitize --user-pip=requirements.txt --user-bindep=bindep.txt --write-bindep=/tmp/src/bindep.txt --write-pip=/tmp/src/requirements.txt
RUN assemble

FROM $EE_BASE_IMAGE
USER root
COPY krb5.conf /etc/krb5.conf
RUN microdnf install which iputils unzip

COPY --from=galaxy /usr/share/ansible /usr/share/ansible

COPY --from=builder /output/ /output/
RUN /output/install-from-bindep && rm -rf /output/wheels
COPY powershell-7.3.2-1.rh.x86_64.rpm /tmp/powershell-7.3.2-1.rh.x86_64.rpm
RUN rpm -i /tmp/powershell-7.3.2-1.rh.x86_64.rpm
ADD powercli.tar.gz /opt/microsoft/powershell/7/Modules
WORKDIR /opt/microsoft/powershell/7/Modules
RUN mv VMware-PowerCLI-13.0.0-20829139/* .
LABEL ansible-execution-environment=true
